services:
    _defaults:
        autowire: true
        autoconfigure: true

    WpConsulting\TouchIdBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Doctrine/'
            - '../src/Entity/'
            - '../src/Installer/'
            - '../src/TouchIdBundle.php'

    WpConsulting\TouchIdBundle\Installer\ProjectConfigurator: ~

    WpConsulting\TouchIdBundle\Controller\TouchIdController:
        tags: ['controller.service_arguments']
