services:
    _defaults:
        autowire: true
        autoconfigure: true

    WpConsulting\PasskeyBundle\:
        resource: '../src/'
        exclude:
            - '../src/Command/PasskeyConfigureCommand.php'
            - '../src/DependencyInjection/'
            - '../src/Doctrine/'
            - '../src/Entity/'
            - '../src/Installer/'
            - '../src/PasskeyBundle.php'

    WpConsulting\PasskeyBundle\Controller\PasskeyController:
        tags: ['controller.service_arguments']
